In [135]:
pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\prajw\miniconda\lib\site-packages (3.10.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\prajw\miniconda\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\prajw\miniconda\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\prajw\miniconda\lib\site-packages (from matplotlib) (4.58.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\prajw\miniconda\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\prajw\miniconda\lib\site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in c:\users\prajw\miniconda\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\prajw\miniconda\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\prajw\miniconda\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\prajw\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\prajw\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [136]:
import numpy as np
import pandas as pd

In [137]:
df=pd.read_csv(r"..\file\Countries.csv")
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [138]:
#how many rows and column
df.shape

(194, 64)

In [139]:
#list columns name
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [140]:
df.dtypes

country              object
country_long         object
currency             object
capital_city         object
region               object
                     ...
democracy_score     float64
democracy_type       object
median_age          float64
political_leader     object
title                object
Length: 64, dtype: object

In [141]:
#mean population across countries
df["population"].mean()

np.float64(40788877.788659796)

In [142]:
#unique values of continent
df["continent"].unique()

array(['Asia', 'Europe', 'Africa', 'Americas', 'Oceania'], dtype=object)

In [143]:
#how many countries has life expentency greater than 80
df[df["life_expectancy"]>80]["country"].count()

np.int64(28)

In [144]:
#Display the country, capital_city, and currency for the first 10 countries
df[["country","capital_city","currency"]]

                country      capital_city            currency
0           Afghanistan             Kabul      Afghan afghani
1               Albania            Tirana        Albanian lek
2               Algeria           Algiers      Algerian dinar
3               Andorra  Andorra la Vella                Euro
4                Angola            Luanda      Angolan kwanza
..                  ...               ...                 ...
189             Vietnam             Hanoi     Vietnamese dong
190  West Bank and Gaza          Ramallah  Israeli new shekel
191               Yemen            Sana'a         Yemeni rial
192              Zambia            Lusaka  New Zambian kwacha
193            Zimbabwe            Harare         U.S. dollar

[194 rows x 3 columns]

In [145]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [146]:
#Sort the dataset by gdp in descending order and show the top 5 countries.
df.sort_values("gdp").head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
179,Tuvalu,Tuvalu,Australian dollar,Funafuti,Polynesia,Oceania,Tuvaluan,-8.000000,178.000000,18.0,...,11312,6.25000,3900,7412,0.0,0.0,Unknown,21.0,Kausea Natano,Prime Minister
119,Nauru,Republic of Nauru,Australian dollar,Yaren,Micronesia,Oceania,Nauruan,-0.533333,166.916667,4.0,...,12668,10.52630,0,12668,0.0,0.0,Unknown,16.3,Lionel Aingimea,President
130,Palau,Republic of Palau,U.S. dollar,Ngerulmud,Micronesia,Oceania,Palauan,7.500000,134.500000,43.0,...,18055,6.25000,3258,14797,0.0,0.0,Unknown,31.7,Thomas Remengesau Jr.,President
87,Kiribati,Republic of Kiribati,Australian dollar,South Tarawa,Micronesia,Oceania,I-Kiribati,1.416667,173.000000,340.0,...,131232,6.66667,56354,74878,0.0,0.0,Unknown,18.0,Taneti Maamau,President
106,Marshall Islands,Republic of the Marshall Islands,U.S. dollar,Majuro,Micronesia,Oceania,Marshallese,9.000000,168.000000,86.0,...,41569,6.06061,8929,32640,0.0,0.0,Unknown,21.6,David Kabua,President

In [147]:
#Count the number of countries in each region.
df.groupby("region")["country"].count()

region
Australia and New Zealand     2
Caribbean                    13
Central America               8
Central Asia                  5
Eastern Africa               17
Eastern Asia                  5
Eastern Europe               10
Melanesia                     4
Micronesia                    5
Middle Africa                10
Northern Africa               6
Northern America              2
Northern Europe              10
Polynesia                     3
South America                12
South-Eastern Asia           11
Southern Africa               5
Southern Asia                 9
Southern Europe              15
Western Africa               16
Western Asia                 17
Western Europe                9
Name: country, dtype: int64

In [148]:
#Find the country with the highest urban_population.
df[df["urban_population"]== df["urban_population"].max()]["country"]

34    China
Name: country, dtype: object

In [149]:
# Check if there are any missing values in the inflation column.
df["inflation"].isna().any()

np.True_

In [150]:
#Filter the dataset to show only countries in the Africa continent.
df[df["continent"]=="Africa"]

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
17,Benin,Republic of Benin,West African CFA franc,Porto-Novo,Western Africa,Africa,Beninese,9.500000,2.250000,39500.0,...,13352864,7.40741,6738656,6614208,2.46,5.74,Hybrid regime,13.6,Patrice Talon,President
21,Botswana,Republic of Botswana,Botswana pula,Gaborone,Southern Africa,Africa,Motswana,-22.000000,24.000000,258620.0,...,2630296,11.11110,730591,1899705,3.12,7.81,Flawed democracy,19.7,Mokgweetsi Masisi,President
25,Burkina Faso,Burkina Faso,West African CFA franc,Ouagadougou,Western Africa,Africa,Burkinabe,13.000000,-2.000000,121430.0,...,22673762,16.90140,15446047,7227715,3.19,4.75,Hybrid regime,12.9,Roch Marc Christian Kaboré,President
26,Burundi,Republic of Burundi,Burundi franc,Bujumbura,Eastern Africa,Africa,Burundian,-3.500000,30.000000,20330.0,...,12889576,38.21140,11031286,1858290,1.48,2.33,Authoritarian,11.9,Pierre Nkurunziza,President
27,Cabo Verde,Republic of Cabo Verde,Cabo Verde escudo,Praia,Western Africa,Africa,Cape Verdian,16.000000,-24.000000,790.0,...,593149,38.88890,192507,400642,3.95,7.88,Flawed democracy,22.9,NaN,NaN
29,Cameroon,Republic of Cameroon,Central African CFA franc,Yaoundé,Middle Africa,Africa,Cameroonian,6.000000,12.000000,97500.0,...,27914536,33.88890,11519492,16395044,1.81,3.28,Authoritarian,13.6,Paul Biya,President
31,Central African Republic,Central African Republic,Central African CFA franc,Bangui,Middle Africa,Africa,Central African,7.000000,21.000000,50800.0,...,5579144,12.85710,3173417,2405727,1.65,1.52,Authoritarian,10.8,Faustin-Archange Touadéra,President
32,Chad,Republic of Chad,Central African CFA franc,N'Djamena,Middle Africa,Africa,Chadian,15.000000,19.000000,502380.0,...,17723315,25.88830,13458554,4264761,2.13,1.61,Authoritarian,11.2,Idriss Déby,President
36,Comoros,Union of the Comoros,Comorian franc,Moroni,Eastern Africa,Africa,Comoran,-12.166667,44.250000,1310.0,...,836774,16.66670,586880,249894,2.80,3.71,Authoritarian,16.3,Azali Assoumani,President
37,Congo,Republic of Congo,Central African CFA franc,Brazzaville,Middle Africa,Africa,Congolese,-1.000000,15.000000,106280.0,...,5970424,14.56950,1866593,4103831,2.17,3.31,Authoritarian,14.3,Denis Sassou Nguesso,President
39,Côte d'Ivoire,Republic of Côte d'Ivoire,West African CFA franc,Yamoussoukro,Western Africa,Africa,Ivorian,8.000000,-5.000000,212000.0,...,28160542,14.17320,13330919,14829623,2.65,4.15,Hybrid regime,13.8,Alassane Ouattara,President
45,Dem. Rep. Congo,Democratic Republic of the Congo,Congolese franc,Kinshasa,Middle Africa,Africa,Congolese,0.000000,25.000000,335720.0,...,99010212,12.80000,52636799,46373413,1.51,1.49,Authoritarian,11.7,Félix Tshisekedi,President
47,Djibouti,Republic of Djibouti,Djibouti franc,Djibouti,Eastern Africa,Africa,Djibouti,11.500000,43.000000,17020.0,...,1120849,26.15380,242328,878521,1.10,2.87,Authoritarian,20.0,Ismaïl Omar Guelleh,President
51,Egypt,Arab Republic of Egypt,Egyptian pound,Cairo,Northern Africa,Africa,Egyptian,27.000000,30.000000,39710.0,...,110990103,27.58040,63300985,47689118,1.38,3.36,Authoritarian,20.1,Abdel Fattah el-Sisi,President
53,Equatorial Guinea,Republic of Equatorial Guinea,Central African CFA franc,Malabo,Middle Africa,Africa,Equatorial Guinean,2.000000,10.000000,1885.2,...,1674908,31.00000,435309,1239599,1.34,1.92,Authoritarian,16.8,Teodoro Obiang Nguema Mbasogo,President
54,Eritrea,State of Eritrea,Eritrean nakfa,Asmara,Eastern Africa,Africa,Eritrean,15.000000,39.000000,75920.0,...,3684032,22.00000,2113713,1570319,0.97,2.37,Authoritarian,14.5,Isaias Afwerki,President
56,Eswatini,Kingdom of Eswatini,Swazi lilangeni,Lobamba,Southern Africa,Africa,Swazi,-26.500000,31.500000,12220.0,...,1201670,13.51350,906348,295322,1.59,3.03,Authoritarian,17.7,Mswati III,King
57,Ethiopia,Federal Democratic Republic of Ethiopia,Ethiopian birr,Addis Ababa,Eastern Africa,Africa,Ethiopian,8.000000,38.000000,384761.0,...,123379924,41.48940,95420799,27959125,2.23,3.35,Authoritarian,14.7,Abiy Ahmed,Prime Minister
61,Gabon,Gabonese Republic,Central African CFA franc,Libreville,Middle Africa,Africa,Gabonese,-1.000000,11.750000,22126.4,...,2388992,15.38460,221340,2167652,2.20,3.61,Authoritarian,17.7,Ali Bongo Ondimba,President
64,Ghana,Republic of Ghana,New Ghanaian cedi,Accra,Western Africa,Africa,Ghanaian,8.000000,-2.000000,126037.0,...,33475870,14.54550,13853989,19621881,3.76,6.63,Flawed democracy,16.6,Nana Akufo-Addo,President
68,Guinea,Republic of Guinea,Guinean franc,Conakry,Western Africa,Africa,Guinean,11.000000,-10.000000,145000.0,...,13859341,29.62960,8638804,5220537,2.34,3.14,Authoritarian,13.9,Alpha Condé,President
69,Guinea-Bissau,Republic of Guinea-Bissau,West African CFA franc,Bissau,Western Africa,Africa,Guinea-Bissauan,12.000000,-15.000000,8151.1,...,2105566,13.72550,1157198,948368,2.53,1.98,Authoritarian,14.5,Umaro Sissoco Embaló,President
86,Kenya,Republic of Kenya,Kenyan shilling,Nairobi,Eastern Africa,Africa,Kenyan,1.000000,38.000000,276300.0,...,54027487,23.42860,38358435,15669052,2.41,5.11,Hybrid regime,15.4,Uhuru Kenyatta,President
94,Lesotho,Kingdom of Lesotho,Lesotho loti,Maseru,Southern Africa,Africa,Mosotho,-29.500000,28.500000,26000.0,...,2305825,26.44630,1615392,690433,2.63,6.64,Flawed democracy,18.2,Tom Thabane,Prime Minister
95,Liberia,Republic of Liberia,U.S. dollar,Monrovia,Western Africa,Africa,Liberian,6.500000,-9.500000,19540.4,...,5302681,10.95890,2488813,2813868,2.48,5.35,Hybrid regime,14.2,George Weah,President
96,Libya,Socialist People's Libyan Arab Jamahiriya,Libyan dinar,Tripoli,Northern Africa,Africa,Libyan,25.000000,17.000000,153500.0,...,6812341,16.47060,1273772,5538569,1.40,2.19,Authoritarian,22.6,Fayez al-Sarraj,Prime Minister
100,Madagascar,Republic of Madagascar,Malagasy ariary,Antananarivo,Eastern Africa,Africa,Malagasy,-20.000000,47.000000,408950.0,...,29611714,18.54300,17801970,11809744,2.82,5.22,Hybrid regime,15.1,Andry Rajoelina,President
101,Malawi,Republic of Malawi,Malawi kwacha,Lilongwe,Eastern Africa,Africa,Malawian,-13.500000,34.000000,56500.0,...,20405317,22.91670,16736441,3668876,2.66,5.49,Hybrid regime,13.1,Peter Mutharika,President
104,Mali,Republic of Mali,West African CFA franc,Bamako,Western Africa,Africa,Malian,17.000000,-4.000000,412010.0,...,22593590,28.57140,12327741,10265849,2.22,5.41,Hybrid regime,11.3,Ibrahim Boubacar Keïta,President
107,Mauritania,Islamic Republic of Mauritania,Mauritanian ouguiya,Nouakchott,Western Africa,Africa,Mauritanian,20.000000,-12.000000,396610.0,...,4736139,20.26140,2040187,2695952,2.47,3.82,Authoritarian,13.8,Mohamed Ould Ghazouani,President
108,Mauritius,Republic of Mauritius,Mauritian rupee,Port Louis,Eastern Africa,Africa,Mauritian,-20.283333,57.550000,860.0,...,1262523,20.00000,747287,515236,2.75,8.22,Full democracy,33.1,Pravind Jugnauth,Prime Minister
115,Morocco,Kingdom of Morocco,Moroccan dirham,Rabat,Northern Africa,Africa,Moroccan,32.000000,-5.000000,303820.0,...,37457971,24.05060,13261620,24196351,1.78,4.99,Hybrid regime,25.0,Mohammed VI,King
116,Mozambique,Republic of Mozambique,New Mozambican metical,Maputo,Eastern Africa,Africa,Mozambican,-18.250000,35.000000,414138.0,...,32969518,42.40000,20379448,12590070,2.39,3.85,Authoritarian,13.0,Filipe Nyusi,President
118,Namibia,Republic of Namibia,Namibian dollar,Windhoek,Southern Africa,Africa,Namibian,-22.000000,17.000000,388100.0,...,2567012,44.23080,1181955,1385057,4.13,6.25,Flawed democracy,17.4,Hage Geingob,President
124,Niger,Republic of Niger,West African CFA franc,Niamey,Western Africa,Africa,Nigerien,16.000000,8.000000,465970.0,...,26207977,25.90360,21780401,4427576,2.67,3.76,Authoritarian,10.5,Mahamadou Issoufou,President
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.000000,8.000000,694500.0,...,218541212,3.61111,101575770,116965442,2.14,4.44,Hybrid regime,13.2,Muhammadu Buhari,President
141,Rwanda,Republic of Rwanda,Rwandan franc,Kigali,Eastern Africa,Africa,Rwandan,-2.000000,30.000000,18117.0,...,13776698,61.25000,11335329,2441369,1.49,3.35,Authoritarian,15.2,Paul Kagame,President
144,São Tomé and Principe,Democratic Republic of São Tomé and Principe,São Tomé and Principe dobra,São Tomé,Middle Africa,Africa,Sao Tomean,1.000000,7.000000,440.0,...,227380,14.54550,55128,172252,0.00,0.00,Unknown,14.6,Evaristo Carvalho,President
146,Senegal,Republic of Senegal,West African CFA franc,Dakar,Western Africa,Africa,Senegalese,14.000000,-14.000000,88780.0,...,17316449,44.24240,8816497,8499952,3.03,6.15,Flawed democracy,14.0,Macky Sall,President
148,Seychelles,Republic of Seychelles,Seychelles rupee,Victoria,Eastern Africa,Africa,Seychellois,-4.583333,55.666667,15.5,...,100060,22.85710,41629,58431,2.66,0.00,Unknown,28.8,Danny Faure,President
149,Sierra Leone,Republic of Sierra Leone,Sierra Leonean leone,Freetown,Western Africa,Africa,Sierra Leonean,8.500000,-11.500000,39490.0,...,8605718,12.32880,4833746,3771972,2.58,4.66,Hybrid regime,15.1,Julius Maada Bio,President
154,Somalia,Somali Democratic Republic,Somali shilling,Mogadishu,Eastern Africa,Africa,Somali,10.000000,49.000000,441250.0,...,17597511,19.70800,9269665,8327846,1.37,0.00,Unknown,11.3,Hassan Ali Khayre,Prime Minister
155,South Africa,Republic of South Africa,South African rand,Pretoria,Southern Africa,Africa,South African,-29.000000,24.000000,963410.0,...,59893885,46.50000,18965399,40928486,3.52,7.24,Flawed democracy,23.3,Cyril Ramaphosa,President
156,South Sudan,Republic of South Sudan,South Sudanese Pound,Juba,Middle Africa,Africa,South Sudanese,7.000000,30.000000,282510.0,...,10913164,32.36360,8638206,2274958,1.71,0.00,Unknown,12.5,Salva Kiir Mayardit,President
162,Sudan,Republic of the Sudan,Sudanese pound,Khartoum,Northern Africa,Africa,Sudanese,15.000000,30.000000,694058.0,...,46874204,30.51640,30020115,16854089,1.08,2.15,Authoritarian,14.5,Abdel Fattah al-Burhan,Leader of the Sovereignty Council
168,Tanzania,United Republic of Tanzania,Tanzanian shilling,Dodoma,Eastern Africa,Africa,Tanzanian,-6.000000,35.000000,395212.0,...,65497748,36.85570,41471864,24025884,2.16,5.41,Hybrid regime,13.0,John Magufuli,President
171,The Gambia,Republic of The Gambia,Gambian dalasi,Banjul,Western Africa,Africa,Gambian,13.466667,-16.566667,6050.0,...,2705992,8.62069,978162,1727830,2.49,4.31,Hybrid regime,13.1,Adama Barrow,President
173,Togo,Republic of Togo,West African CFA franc,Lomé,Western Africa,Africa,Togolese,8.000000,1.166667,38200.0,...,8848699,18.68130,4962262,3886437,2.63,3.10,Authoritarian,14.8,Faure Gnassingbé,President
176,Tunisia,Republic of Tunisia,Tunisian dinar,Tunis,Northern Africa,Africa,Tunisian,34.000000,9.000000,97310.0,...,12356117,26.26730,3680393,8675724,2.64,6.41,Flawed democracy,28.0,Kaïs Saïed,President
180,Uganda,Republic of Uganda,Ugandan shilling,Kampala,Eastern Africa,Africa,Ugandan,1.000000,32.000000,144150.0,...,47249585,33.81300,34889566,12360019,1.98,5.20,Hybrid regime,12.2,Yoweri Museveni,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [151]:
#Calculate the total co2_emissions across all countries.
df["co2_emissions"].sum()

np.float64(32320772.856)

In [152]:
#Display the country and democracy_score for countries with a democracy_type of ”Full democracy”.
df[df["democracy_type"]=="Full democracy"][["country","democracy_score"]]

            country  democracy_score
8         Australia             9.09
9           Austria             8.29
30           Canada             9.15
38       Costa Rica             8.07
46          Denmark             9.22
59          Finland             9.14
63          Germany             8.68
74          Iceland             9.58
79          Ireland             9.15
99       Luxembourg             8.81
105           Malta             8.21
108       Mauritius             8.22
121     Netherlands             8.89
122     New Zealand             9.26
127          Norway             9.87
157           Spain             8.08
164          Sweden             9.39
165     Switzerland             9.03
183  United Kingdom             8.53
185         Uruguay             8.38

In [153]:
#Group the dataset by continent and calculate the average gdp for each continent.
df.groupby("continent")["gdp"].mean()

continent
Africa      5.466804e+10
Americas    9.675583e+11
Asia        7.989775e+11
Europe      5.400586e+11
Oceania     1.402479e+11
Name: gdp, dtype: float64

In [154]:
#Filter countries where internet_pct is above 90 and unemployment_pct is below 5.
df[(df["internet_pct"]>90) & (df["unemployment_pct"]<5)]["country"]

8                 Australia
9                   Austria
11                  Bahrain
46                  Denmark
63                  Germany
74                  Iceland
79                  Ireland
80                   Israel
88                    Korea
89                   Kuwait
99               Luxembourg
102                Malaysia
121             Netherlands
122             New Zealand
127                  Norway
128                    Oman
138                   Qatar
150               Singapore
165             Switzerland
182    United Arab Emirates
183          United Kingdom
184           United States
Name: country, dtype: object

In [155]:
#Replace missing values in inflation with the median inflation value of the dataset
df["inflation"].fillna(df["inflation"].median(),inplace=True)

C:\Users\prajw\AppData\Local\Temp\ipykernel_592\3856720647.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["inflation"].fillna(df["inflation"].median(),inplace=True)

In [156]:
df["inflation"].isna().any()

np.False_

In [157]:
#Create a new column population_density by dividing population by land_area.
df["population_density"]=df["population"]/df["land_area"]
df["population_density"]

0       63.058692
1      101.300511
2       18.853118
3      169.838298
4       28.546552
          ...
189    313.266660
190    837.809302
191     63.822971
192     26.927555
193     42.188282
Name: population_density, Length: 194, dtype: float64

In [158]:
#Find the top 3 countries in Southern Asia with the highest health_expenditure_pct_gd
df.nlargest(3,"health_expenditure_pct_gdp")[["country","gdp"]]

           country           gdp
179         Tuvalu  6.034940e+07
184  United States  2.546270e+13
130          Palau  2.178000e+08

In [159]:
#Group the dataset by democracy_type and compute the median life_expectancy for each type
df.groupby("democracy_type")["life_expectancy"].median()

democracy_type
Authoritarian       68.0
Flawed democracy    74.0
Full democracy      82.0
Hybrid regime       69.0
Unknown             71.0
Name: life_expectancy, dtype: float64

In [160]:
#Filter countries where co2_emissions is above the 75th percentile of the
#dataset.

df[df["co2_emissions"]>df["co2_emissions"].quantile(0.75)][["country","co2_emissions"]]

                  country  co2_emissions
2                 Algeria       161563.0
6               Argentina       154536.0
8               Australia       378997.0
12             Bangladesh        85493.1
15                Belgium        85364.1
22                 Brazil       414139.0
30                 Canada       516874.0
33                  Chile        84827.8
34                  China     10944700.0
35               Colombia        79057.6
43         Czech Republic        88835.2
51                  Egypt       210752.0
60                 France       267155.0
63                Germany       603350.0
75                  India      2200840.0
76              Indonesia       563197.0
77                   Iran       616561.0
78                   Iraq       163512.0
81                  Italy       281287.0
83                  Japan      1014060.0
85             Kazakhstan       211897.0
88                  Korea       569682.0
89                 Kuwait        92308.9
102              Malaysia       245139.0
109                Mexico       383131.0
115               Morocco        66719.5
121           Netherlands       130315.0
125               Nigeria       111978.0
128                  Oman        71041.5
129              Pakistan       184111.0
135           Philippines       133471.0
136                Poland       279224.0
138                 Qatar        87578.3
139               Romania        68664.0
140                Russia      1618270.0
145          Saudi Arabia       513556.0
155          South Africa       393242.0
157                 Spain       202706.0
169              Thailand       265479.0
177                Turkey       407406.0
178          Turkmenistan        63655.0
181               Ukraine       165664.0
182  United Arab Emirates       188089.0
183        United Kingdom       308650.0
184         United States      4320530.0
186            Uzbekistan       115578.0
188             Venezuela        72509.0
189               Vietnam       355323.0

In [161]:
# Merge the dataset with itself to compare gdp of countries in the same region
# (self-join on region).
df_merged = df.merge(df, on="region", suffixes=('_left', '_right'))
df_merged = df_merged[df_merged["country_left"] != df_merged["country_right"]]
df_merged[["country_left","gdp_left","country_right","gdp_right"]].head(35)

   country_left      gdp_left           country_right     gdp_right
1   Afghanistan  1.458310e+10              Bangladesh  4.602010e+11
2   Afghanistan  1.458310e+10                  Bhutan  2.539550e+09
3   Afghanistan  1.458310e+10                   India  3.385090e+12
4   Afghanistan  1.458310e+10                    Iran  3.885440e+11
5   Afghanistan  1.458310e+10                Maldives  6.189870e+09
6   Afghanistan  1.458310e+10                   Nepal  4.082820e+10
7   Afghanistan  1.458310e+10                Pakistan  3.765330e+11
8   Afghanistan  1.458310e+10               Sri Lanka  7.440360e+10
10      Albania  1.888210e+10                 Andorra  3.352030e+09
11      Albania  1.888210e+10  Bosnia and Herzegovina  2.452750e+10
12      Albania  1.888210e+10                 Croatia  7.096460e+10
13      Albania  1.888210e+10                  Cyprus  2.843910e+10
14      Albania  1.888210e+10                  Greece  2.190660e+11
15      Albania  1.888210e+10                   Italy  2.010430e+12
16      Albania  1.888210e+10                   Malta  1.776530e+10
17      Albania  1.888210e+10              Montenegro  6.095980e+09
18      Albania  1.888210e+10         North Macedonia  1.356310e+10
19      Albania  1.888210e+10                Portugal  2.519450e+11
20      Albania  1.888210e+10              San Marino  1.855380e+09
21      Albania  1.888210e+10                  Serbia  6.350180e+10
22      Albania  1.888210e+10                Slovenia  6.211780e+10
23      Albania  1.888210e+10                   Spain  1.397510e+12
25      Algeria  1.919130e+11                   Egypt  4.767480e+11
26      Algeria  1.919130e+11                   Libya  4.575230e+10
27      Algeria  1.919130e+11                 Morocco  1.341820e+11
28      Algeria  1.919130e+11                   Sudan  5.166220e+10
29      Algeria  1.919130e+11                 Tunisia  4.666490e+10
30      Andorra  3.352030e+09                 Albania  1.888210e+10
32      Andorra  3.352030e+09  Bosnia and Herzegovina  2.452750e+10
33      Andorra  3.352030e+09                 Croatia  7.096460e+10
34      Andorra  3.352030e+09                  Cyprus  2.843910e+10
35      Andorra  3.352030e+09                  Greece  2.190660e+11
36      Andorra  3.352030e+09                   Italy  2.010430e+12
37      Andorra  3.352030e+09                   Malta  1.776530e+10
38      Andorra  3.352030e+09              Montenegro  6.095980e+09

In [162]:
#Calculate the percentage of urban_population relative to population for each country.
df["urban_population_per"]=df["urban_population"]/df["population"]*100
df.nlargest(20,"urban_population_per")[["country","population","urban_population","urban_population_per"]]

         country  population  urban_population  urban_population_per
89        Kuwait     4268873           4268873            100.000000
112       Monaco       36469             36469            100.000000
119        Nauru       12668             12668            100.000000
150    Singapore     5637022           5637022            100.000000
138        Qatar     2695122           2676741             99.317990
15       Belgium    11669446          11453911             98.152997
143   San Marino       33660             32897             97.733214
185      Uruguay     3422794           3275203             95.687996
105        Malta      523417            496592             94.875023
74       Iceland      381900            358955             93.991883
121  Netherlands    17703090          16443692             92.885999
80        Israel     9550600           8859423             92.762999
6      Argentina    46234830          42696478             92.346999
83         Japan   125124989         115058684             91.955000
99    Luxembourg      650774            597938             91.881052
84        Jordan    11285869          10363475             91.827001
61         Gabon     2388992           2167652             90.735005
11       Bahrain     1472233           1321226             89.742996
93       Lebanon     5489739           4900251             89.262003
164       Sweden    10486941           9280104             88.492002

In [163]:
#. Find countries where renewable_energy_consumption_pct is greater than
#fossil_energy_consumption_pct
df[df["renewable_energy_consumption_pct"]>df["fossil_energy_consumption_pct"]]["country"]

4                   Angola
5      Antigua and Barbuda
13                Barbados
16                  Belize
17                   Benin
              ...
174                  Tonga
185                Uruguay
187                Vanuatu
192                 Zambia
193               Zimbabwe
Name: country, Length: 62, dtype: object

In [164]:
#Group by continent and find the country with the maximum fertility_rate
#in each continent.
df.loc[df.groupby("continent")["fertility_rate"].idxmax()][["country","continent","fertility_rate"]]

             country continent  fertility_rate
124            Niger    Africa           6.820
71             Haiti  Americas           2.814
0        Afghanistan      Asia           4.643
43    Czech Republic    Europe           1.830
153  Solomon Islands   Oceania           3.983

In [165]:
#Create a pivot table comparing median_age and fertility_rate across continent
#and democracy_type, handling missing values.
pd.pivot_table(
        df,
        values=["median_age", "fertility_rate"],
        index="continent",
        columns="democracy_type",
        aggfunc="median",
        fill_value=0
    )

               fertility_rate                                                \
democracy_type  Authoritarian Flawed democracy Full democracy Hybrid regime
continent
Africa                 4.2140           2.9045          1.410         4.418
Americas               2.2110           1.8850          1.493         2.395
Asia                   2.3855           2.0310          0.000         2.055
Europe                 1.4880           1.5850          1.555         1.495
Oceania                0.0000           3.2150          1.670         2.475

                          median_age                                  \
democracy_type Unknown Authoritarian Flawed democracy Full democracy
continent
Africa          4.1460         14.50            18.95          33.10
Americas        1.5950         24.20            25.40          31.50
Asia            1.7350         25.40            25.60           0.00
Europe          1.2700         35.75            38.90          36.55
Oceania         3.2705          0.00            18.00          33.05


democracy_type Hybrid regime Unknown
continent
Africa                 13.20   13.55
Americas               19.80   29.10
Asia                   23.65   27.70
Europe                 34.45   41.30
Oceania                23.00   17.95

In [166]:
# Create a pivot table showing the average military_expenditure_pct_gdp
#by region and democracy_type.
pd.pivot_table(
    df,
    values="military_expenditure_pct_gdp",
    index="region",
    columns="democracy_type",
    aggfunc="mean",
    fill_value=0
)

democracy_type,Authoritarian,Flawed democracy,Full democracy,Hybrid regime,Unknown
region,,,,,
Australia and New Zealand,0.000000,0.000000,1.674700,0.000000,0.00000
Caribbean,2.876210,0.983766,0.000000,0.188541,0.00000
Central America,0.603582,0.827133,0.000000,1.141783,1.25358
Central Asia,2.083232,0.000000,0.000000,1.669210,0.00000
Eastern Africa,4.296348,0.000000,0.169558,1.272361,1.49930
Eastern Asia,1.736340,1.501991,0.000000,0.000000,0.00000
Eastern Europe,2.617940,1.740867,0.000000,1.819982,0.00000
Melanesia,0.000000,0.375261,0.000000,1.650630,0.00000
Middle Africa,1.662322,0.000000,0.000000,0.000000,2.36822
Northern Africa,5.847363,2.828980,0.000000,4.183510,0.00000
Northern America,0.000000,3.483220,1.315150,0.000000,0.00000
Northern Europe,0.000000,2.152553,1.501350,0.000000,0.00000
South America,0.179230,1.577840,2.256310,1.544460,0.00000
South-Eastern Asia,2.031441,1.382315,0.000000,1.318440,3.26223
Southern Africa,1.698020,2.011451,0.000000,0.000000,0.00000
Southern Asia,1.829010,2.266665,0.000000,2.146680,0.00000
Southern Europe,0.000000,2.212831,0.942220,1.398642,0.00000
Western Africa,1.854148,0.928594,0.000000,1.350555,0.00000
Western Asia,5.295025,5.171620,0.000000,2.698570,0.00000
Western Europe,0.000000,1.513595,0.980095,0.000000,0.00000

In [167]:
#Filter countries with birth_rate above 20 and death_rate below 10, then
#sort by fertility_rate
df[(df["birth_rate"]>20) & (df["death_rate"]<10)].sort_values("fertility_rate").head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title,population_density,urban_population_per
120,Nepal,Nepal,Nepalese rupee,Kathmandu,Southern Asia,Asia,Nepalese,28.0,84.00,41210.0,...,23994819,6552761,2.34,5.18,Hybrid regime,20.0,KP Sharma Oli,Prime Minister,213.097872,21.450999
123,Nicaragua,Republic of Nicaragua,Nicaraguan gold cordoba,Managua,Central America,Americas,Nicaraguan,13.0,-85.00,50650.0,...,2810208,4138184,2.20,3.63,Authoritarian,20.9,Daniel Ortega,President,57.739671,59.555995
72,Honduras,Republic of Honduras,Honduran lempira,Tegucigalpa,Central America,Americas,Honduran,15.0,-86.50,35110.0,...,4214875,6217985,1.61,5.63,Hybrid regime,19.8,Juan Orlando Hernández,President,93.242113,59.600004
67,Guatemala,Republic of Guatemala,Guatemalan quetzal,Guatemala City,Central America,Americas,Guatemalan,15.5,-90.25,38560.0,...,8216182,9141704,2.18,5.60,Hybrid regime,18.5,Alejandro Giammattei,President,161.981019,52.665999
70,Guyana,Co-operative Republic of Guyana,Guyana dollar,Georgetown,South America,Americas,Guyanese,5.0,-59.00,12412.5,...,590192,218534,2.94,6.67,Flawed democracy,21.8,David A. Granger,President,4.108336,27.022007

In [168]:
#Compute the correlation between gdp and health_expenditure_capita for
#countries in Europe.
df_europe = df[df["continent"] == "Europe"]
correlation = df_europe["gdp"].corr(df_europe["health_expenditure_capita"])
print(correlation)

0.32368770527658247

In [169]:
df[(df["armed_forces"]>0) & df["military_expenditure_pct_gdp"].isna()][["country","armed_forces","military_expenditure_pct_gdp"]]

                      country  armed_forces  military_expenditure_pct_gdp
13                   Barbados        1000.0                           NaN
18                     Bhutan        6000.0                           NaN
38                 Costa Rica       10000.0                           NaN
44   Dem. People's Rep. Korea     1469000.0                           NaN
103                  Maldives        5000.0                           NaN
144     São Tomé and Principe        1000.0                           NaN
163                  Suriname        2000.0                           NaN
170               The Bahamas        2000.0                           NaN

In [170]:
#Create a new column categorizing countries into ”Low”, ”Medium”, and ”High”
#GDP based on quartiles of the gdp column.
df["gdp_category"] = pd.qcut(df["gdp"], q=3, labels=["Low", "Medium", "High"])
df[["country","gdp","gdp_category"]].head(25)

                   country           gdp gdp_category
0              Afghanistan  1.458310e+10          Low
1                  Albania  1.888210e+10       Medium
2                  Algeria  1.919130e+11         High
3                  Andorra  3.352030e+09          Low
4                   Angola  1.067140e+11       Medium
5      Antigua and Barbuda  1.757600e+09          Low
6                Argentina  6.327700e+11         High
7                  Armenia  1.950280e+10       Medium
8                Australia  1.675420e+12         High
9                  Austria  4.714000e+11         High
10              Azerbaijan  7.872110e+10       Medium
11                 Bahrain  4.439080e+10       Medium
12              Bangladesh  4.602010e+11         High
13                Barbados  5.637910e+09          Low
14                 Belarus  7.279350e+10       Medium
15                 Belgium  5.786040e+11         High
16                  Belize  2.824080e+09          Low
17                   Benin  1.740170e+10       Medium
18                  Bhutan  2.539550e+09          Low
19                 Bolivia  4.306890e+10       Medium
20  Bosnia and Herzegovina  2.452750e+10       Medium
21                Botswana  2.035230e+10       Medium
22                  Brazil  1.920100e+12         High
23                  Brunei  1.668150e+10       Medium
24                Bulgaria  8.904040e+10       Medium

In [171]:
#For each continent, calculate the ratio of co2_emissions to population
#and identify the country with the highest ratio.
continent_ratio = df.groupby("continent")[["co2_emissions", "population"]].sum()
continent_ratio["co2_per_capita"] = continent_ratio["co2_emissions"] / continent_ratio["population"]
continent_ratio

df["co2_per_capita"] = df["co2_emissions"] / df["population"]
highest_per_country = df.loc[df.groupby("continent")["co2_per_capita"].idxmax()]
highest_per_country[["continent","country"]]

    continent       country
155    Africa  South Africa
30   Americas        Canada
138      Asia         Qatar
99     Europe    Luxembourg
8     Oceania     Australia

In [172]:
#Use a rolling window of 5 countries (sorted by population) to compute the
#average life_expectancy.
df.sort_values("population",inplace=True)
df["life_expectancy"].rolling(5,min_periods=1).mean()

179    65.0
119    64.5
130    66.0
143    66.0
112    66.0
       ...
129    66.6
76     66.4
184    67.2
34     68.2
75     71.0
Name: life_expectancy, Length: 194, dtype: float64

In [173]:
#Apply a custom function to normalize health_expenditure_capita within
#each region to a 0–1 scale.
df["normalized"] = df.groupby("region")["health_expenditure_capita"].transform(lambda x: (x - x.min()) / (x.max() - x.min()))
df[["country","normalized"]]

           country  normalized
179         Tuvalu    1.000000
119          Nauru    0.395039
130          Palau    1.000000
143     San Marino    1.000000
112         Monaco    0.000000
..             ...         ...
129       Pakistan    0.000000
76       Indonesia    0.018644
184  United States    1.000000
34           China    0.091593
75           India    0.023434

[194 rows x 2 columns]

In [174]:
#find countries where the urban_population is more than 50% of the total
#population and electricity_access_pct is below 90.
df.query("urban_population > population / 2 and electricity_access_pct < 90")

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,democracy_score,democracy_type,median_age,political_leader,title,population_density,urban_population_per,gdp_category,co2_per_capita,normalized
144,São Tomé and Principe,Democratic Republic of São Tomé and Principe,São Tomé and Principe dobra,São Tomé,Middle Africa,Africa,Sao Tomean,1.000000,7.000000,440.0,...,0.00,Unknown,14.6,Evaristo Carvalho,President,236.854167,75.755124,Low,0.000621,0.397788
47,Djibouti,Republic of Djibouti,Djibouti franc,Djibouti,Eastern Africa,Africa,Djibouti,11.500000,43.000000,17020.0,...,2.87,Authoritarian,20.0,Ismaïl Omar Guelleh,President,48.354142,78.379960,Low,0.000382,0.065292
53,Equatorial Guinea,Republic of Equatorial Guinea,Central African CFA franc,Malabo,Middle Africa,Africa,Equatorial Guinean,2.000000,10.000000,1885.2,...,1.92,Authoritarian,16.8,Teodoro Obiang Nguema Mbasogo,President,59.711515,74.009975,Low,0.002597,1.000000
118,Namibia,Republic of Namibia,Namibian dollar,Windhoek,Southern Africa,Africa,Namibian,-22.000000,17.000000,388100.0,...,6.25,Flawed democracy,17.4,Hage Geingob,President,3.117992,53.956000,Low,0.001540,0.712180
21,Botswana,Republic of Botswana,Botswana pula,Gaborone,Southern Africa,Africa,Motswana,-22.000000,24.000000,258620.0,...,7.81,Flawed democracy,19.7,Mokgweetsi Masisi,President,4.641180,72.224001,Medium,0.002191,0.668251
171,The Gambia,Republic of The Gambia,Gambian dalasi,Banjul,Western Africa,Africa,Gambian,13.466667,-16.566667,6050.0,...,4.31,Hybrid regime,13.1,Adama Barrow,President,267.390514,63.852000,Low,0.000226,0.000000
107,Mauritania,Islamic Republic of Mauritania,Mauritanian ouguiya,Nouakchott,Western Africa,Africa,Mauritanian,20.000000,-12.000000,396610.0,...,3.82,Authoritarian,13.8,Mohamed Ould Ghazouani,President,4.595070,56.922991,Low,0.000812,0.257034
95,Liberia,Republic of Liberia,U.S. dollar,Monrovia,Western Africa,Africa,Liberian,6.500000,-9.500000,19540.4,...,5.35,Hybrid regime,14.2,George Weah,President,55.052751,53.065006,Low,0.000222,0.242152
37,Congo,Republic of Congo,Central African CFA franc,Brazzaville,Middle Africa,Africa,Congolese,-1.000000,15.000000,106280.0,...,3.31,Authoritarian,14.3,Denis Sassou Nguesso,President,17.482940,68.736006,Low,0.001198,0.276527
96,Libya,Socialist People's Libyan Arab Jamahiriya,Libyan dinar,Tripoli,Northern Africa,Africa,Libyan,25.000000,17.000000,153500.0,...,2.19,Authoritarian,22.6,Fayez al-Sarraj,Prime Minister,3.871660,81.301993,Medium,0.006527,1.000000
123,Nicaragua,Republic of Nicaragua,Nicaraguan gold cordoba,Managua,Central America,Americas,Nicaraguan,13.000000,-85.000000,50650.0,...,3.63,Authoritarian,20.9,Daniel Ortega,President,57.739671,59.555995,Low,0.000659,0.000000
71,Haiti,Republic of Haiti,Haitian gourde,Port-au-Prince,Caribbean,Americas,Haitian,19.000000,-72.416667,18400.0,...,4.91,Hybrid regime,19.3,Jovenel Moïse,President,420.355443,58.820003,Medium,0.000277,0.000000
166,Syrian Arab Republic,Syrian Arab Republic,Syrian pound,Damascus,Western Asia,Asia,Syrian,35.000000,38.000000,139210.0,...,1.43,Authoritarian,17.7,Bashar al-Assad,President,120.488205,56.769002,Low,0.001141,0.000000
44,Dem. People's Rep. Korea,Democratic People's Republic of Korea,Democratic People's Republic of Korean won,Pyongyang,Eastern Asia,Asia,North Korean,40.000000,127.000000,25900.0,...,1.08,Authoritarian,31.9,Kim Jong-un,Chairman of the Workers Party of Korea,216.505407,62.916001,NaN,0.002011,NaN
29,Cameroon,Republic of Cameroon,Central African CFA franc,Yaoundé,Middle Africa,Africa,Cameroonian,6.000000,12.000000,97500.0,...,3.28,Authoritarian,13.6,Paul Biya,President,59.052138,58.732998,Medium,0.000356,0.170646
39,Côte d'Ivoire,Republic of Côte d'Ivoire,West African CFA franc,Yamoussoukro,Western Africa,Africa,Ivorian,8.000000,-5.000000,212000.0,...,4.15,Hybrid regime,13.8,Alassane Ouattara,President,88.555164,52.661000,Medium,0.000387,0.422968
64,Ghana,Republic of Ghana,New Ghanaian cedi,Accra,Western Africa,Africa,Ghanaian,8.000000,-2.000000,126037.0,...,6.63,Flawed democracy,16.6,Nana Akufo-Addo,President,147.125340,58.614999,Medium,0.000580,0.421723
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,3.62,Authoritarian,12.4,João Lourenço,President,28.546552,68.080999,Medium,0.000557,0.136924
155,South Africa,Republic of South Africa,South African rand,Pretoria,Southern Africa,Africa,South African,-29.000000,24.000000,963410.0,...,7.24,Flawed democracy,23.3,Cyril Ramaphosa,President,49.372994,68.334999,High,0.006566,1.000000
125,Nigeria,Federal Republic of Nigeria,Nigerian naira,Abuja,Western Africa,Africa,Nigerian,10.000000,8.000000,694500.0,...,4.44,Hybrid regime,13.2,Muhammadu Buhari,President,239.952142,53.521000,High,0.000512,0.325075

In [175]:
# Group by democracy_type and compute the average gdp only for countries
# with non-missing inflation values.
df_filtered = df[df["inflation"].notna()]  # Keep rows where inflation is NOT missing
df_filtered.groupby("democracy_type")["gdp"].mean()

democracy_type
Authoritarian       4.961138e+11
Flawed democracy    9.759507e+11
Full democracy      8.762052e+11
Hybrid regime       1.063564e+11
Unknown             3.459348e+09
Name: gdp, dtype: float64

In [176]:
# Create a new DataFrame showing the top 5 countries per continent by internet_pct,
# handling ties appropriately.
df['rank'] = df.groupby('continent')['internet_pct'].rank(method='min', ascending=False)
top5_per_continent = df[df['rank'] <= 5].copy()
top5_per_continent

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,democracy_type,median_age,political_leader,title,population_density,urban_population_per,gdp_category,co2_per_capita,normalized,rank
119,Nauru,Republic of Nauru,Australian dollar,Yaren,Micronesia,Oceania,Nauruan,-0.533333,166.916667,4.00,...,Unknown,16.3,Lionel Aingimea,President,633.400000,100.000000,Low,0.003268,0.395039,4.0
5,Antigua and Barbuda,Antigua and Barbuda,East Caribbean dollar,Saint John's,Caribbean,Americas,Antiguan,17.050000,-61.800000,90.00,...,Unknown,31.1,Gaston Browne,Prime Minister,213.097727,24.346491,Low,0.005062,0.435107,1.0
148,Seychelles,Republic of Seychelles,Seychelles rupee,Victoria,Eastern Africa,Africa,Seychellois,-4.583333,55.666667,15.50,...,Unknown,28.8,Danny Faure,President,217.521739,58.395962,Low,0.005983,1.000000,2.0
142,Samoa,Samoa,Samoan tala,Apia,Polynesia,Oceania,Samoan,-13.583333,-172.333333,494.10,...,Unknown,16.7,Tuilaepa Aiono Sailele Malielegaoi,Prime Minister,79.993525,17.616084,Low,0.000929,0.000000,5.0
74,Iceland,Republic of Iceland,Iceland krona,Reykjavík,Northern Europe,Europe,Icelander,65.000000,-18.000000,18720.00,...,Full democracy,32.1,Katrín Jakobsdóttir,Prime Minister,3.787563,93.991883,Medium,0.003788,0.690600,1.0
170,The Bahamas,Commonwealth of The Bahamas,Bahamian dollar,Nassau,Caribbean,Americas,Bahamian,24.250000,-76.000000,140.00,...,Unknown,28.9,Hubert Minnis,Prime Minister,40.957443,83.492039,Low,0.005990,1.000000,2.0
99,Luxembourg,Grand Duchy of Luxembourg,Euro,Luxembourg,Western Europe,Europe,Luxembourger,49.750000,6.166667,1321.36,...,Full democracy,35.0,Xavier Bettel,Prime Minister,252.780777,91.881052,Medium,0.012067,0.585371,4.0
58,Fiji,Republic of Fiji,Fijian dollar,Suva,Melanesia,Oceania,Fijian,-18.000000,175.000000,3116.00,...,Hybrid regime,23.0,Frank Bainimarama,Prime Minister,50.890312,58.228952,Low,0.001106,1.000000,3.0
11,Bahrain,Kingdom of Bahrain,Bahraini dinar,Manama,Western Asia,Asia,Bahraini,26.000000,50.550000,86.00,...,Authoritarian,29.2,Sheikh Hamad bin Isa Al Khalifa,King,1875.456051,89.742996,Medium,0.022055,0.275182,1.0
21,Botswana,Republic of Botswana,Botswana pula,Gaborone,Southern Africa,Africa,Motswana,-22.000000,24.000000,258620.00,...,Flawed democracy,19.7,Mokgweetsi Masisi,President,4.641180,72.224001,Medium,0.002191,0.668251,4.0
138,Qatar,State of Qatar,Qatari riyal,Doha,Western Asia,Asia,Qatari,25.500000,51.250000,740.00,...,Authoritarian,29.6,Sheikh Tamim bin Hamad Al Thani,Emir,234.562402,99.317990,High,0.032495,0.558648,1.0
89,Kuwait,State of Kuwait,Kuwaiti dinar,Kuwait City,Western Asia,Asia,Kuwaiti,29.500000,45.750000,1500.00,...,Authoritarian,35.1,Sheikh Sabah Al-Ahmad Al-Jaber Al-Sabah,Emir,239.555163,100.000000,High,0.021624,0.386257,5.0
122,New Zealand,New Zealand,New Zealand dollar,Wellington,Australia and New Zealand,Oceania,New Zealander,-41.000000,174.000000,101540.00,...,Full democracy,32.8,Jacinda Ardern,Prime Minister,19.460332,86.883999,High,0.006120,0.000000,2.0
127,Norway,Kingdom of Norway,Norwegian krone,Oslo,Northern Europe,Europe,Norwegian,62.000000,10.000000,9859.62,...,Full democracy,35.6,Erna Solberg,Prime Minister,14.980378,83.664005,High,0.006629,1.000000,2.0
46,Denmark,Kingdom of Denmark,Danish krone,Copenhagen,Northern Europe,Europe,Danish,56.000000,10.000000,26199.90,...,Full democracy,37.2,Mette Frederiksen,Prime Minister,147.575925,88.367005,High,0.004634,0.786503,3.0
182,United Arab Emirates,United Arab Emirates,U.A.E. dirham,Abu Dhabi,Western Asia,Asia,Emirati,24.000000,54.000000,3898.00,...,Authoritarian,29.3,Sheikh Khalifa bin Zayed Al Nahyan,President,132.936201,87.543005,High,0.019922,0.559549,1.0
176,Tunisia,Republic of Tunisia,Tunisian dinar,Tunis,Northern Africa,Africa,Tunisian,34.000000,9.000000,97310.00,...,Flawed democracy,28.0,Kaïs Saïed,President,79.532164,70.214000,Medium,0.002371,0.685049,3.0
33,Chile,Republic of Chile,Chilean peso,Santiago,South America,Americas,Chilean,-30.000000,-71.000000,157100.00,...,Flawed democracy,31.3,Sebastián Piñera,President,26.365688,87.912001,High,0.004327,1.000000,5.0
8,Australia,Commonwealth of Australia,Australian dollar,Canberra,Australia and New Zealand,Oceania,Australian,-27.000000,133.000000,3557750.00,...,Full democracy,33.3,Anthony Albanese,Prime Minister,3.377388,86.487999,High,0.014589,1.000000,1.0
145,Saudi Arabia,Kingdom of Saudi Arabia,Saudi Arabian riyal,Riyadh,Western Asia,Asia,Saudi Arabian,25.000000,45.000000,1735960.00,...,Authoritarian,26.2,Salman,King,16.936777,84.729000,High,0.014105,0.322794,1.0
115,Morocco,Kingdom of Morocco,Moroccan dirham,Rabat,Northern Africa,Africa,Moroccan,32.000000,-5.000000,303820.00,...,Hybrid regime,25.0,Mohammed VI,King,83.930027,64.596000,High,0.001781,0.566616,1.0
30,Canada,Canada,Canadian dollar,Ottawa,Northern America,Americas,Canadian,60.000000,-95.000000,577430.00,...,Full democracy,36.4,Justin Trudeau,Prime Minister,4.342146,81.751999,High,0.013277,0.000000,3.0
155,South Africa,Republic of South Africa,South African rand,Pretoria,Southern Africa,Africa,South African,-29.000000,24.000000,963410.00,...,Flawed democracy,23.3,Cyril Ramaphosa,President,49.372994,68.334999,High,0.006566,1.000000,5.0
183,United Kingdom,United Kingdom of Great Britain and Northern I...,Pound sterling,London,Northern Europe,Europe,British,54.000000,-2.000000,172593.00,...,Full democracy,35.9,Rishi Sunak,Prime Minister,276.821440,84.397999,High,0.004609,0.560617,5.0
184,United States,United States of America,U.S. dollar,"Washington, D.C.",Northern America,Americas,American,38.000000,-97.000000,4058100.00,...,Flawed democracy,33.9,Joe Biden,President,36.435143,83.084000,High,0.012963,1.000000,4.0

In [177]:
#Identify outliers in co2_emissions using the IQR method and list the countries with these outliers
Q1 = df['co2_emissions'].quantile(0.25)
Q3 = df['co2_emissions'].quantile(0.75)
print(Q3)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['co2_emissions'] < lower_bound) | (df['co2_emissions'] > upper_bound)]
outlier_countries = outliers[['country', 'co2_emissions']]
outlier_countries

61398.7

                  country  co2_emissions
182  United Arab Emirates       188089.0
85             Kazakhstan       211897.0
8               Australia       378997.0
102              Malaysia       245139.0
145          Saudi Arabia       513556.0
136                Poland       279224.0
181               Ukraine       165664.0
30                 Canada       516874.0
78                   Iraq       163512.0
2                 Algeria       161563.0
6               Argentina       154536.0
157                 Spain       202706.0
88                  Korea       569682.0
81                  Italy       281287.0
155          South Africa       393242.0
183        United Kingdom       308650.0
60                 France       267155.0
169              Thailand       265479.0
63                Germany       603350.0
177                Turkey       407406.0
77                   Iran       616561.0
189               Vietnam       355323.0
51                  Egypt       210752.0
83                  Japan      1014060.0
109                Mexico       383131.0
140                Russia      1618270.0
22                 Brazil       414139.0
129              Pakistan       184111.0
76              Indonesia       563197.0
184         United States      4320530.0
34                  China     10944700.0
75                  India      2200840.0

In [178]:
#For each region, calculate the percentage contribution of each country’s gdp
#to the region’s total gdp.
df['gdp_pct'] = df['gdp'] / (df.groupby('region')['gdp'].transform('sum')) * 100
for region, group in df.groupby('region'):
    print(f"\n--- {region} ---")
    print(group[['country', 'region',"gdp",'gdp_pct']])

--- Australia and New Zealand ---
         country                     region           gdp    gdp_pct
122  New Zealand  Australia and New Zealand  2.472340e+11  12.858996
8      Australia  Australia and New Zealand  1.675420e+12  87.141004

--- Caribbean ---
                            country     region           gdp    gdp_pct
159             St. Kitts and Nevis  Caribbean  9.615630e+08   0.307817
48                         Dominica  Caribbean  6.120480e+08   0.195930
5               Antigua and Barbuda  Caribbean  1.757600e+09   0.562646
161  St. Vincent and the Grenadines  Caribbean  9.485590e+08   0.303654
66                          Grenada  Caribbean  1.256410e+09   0.402204
160                       St. Lucia  Caribbean  2.065030e+09   0.661061
13                         Barbados  Caribbean  5.637910e+09   1.804818
170                     The Bahamas  Caribbean  1.289740e+10   4.128740
175             Trinidad and Tobago  Caribbean  2.789910e+10   8.931112
82                          Jamaica  Caribbean  1.709780e+10   5.473380
41                             Cuba  Caribbean  1.073520e+11  34.365724
49               Dominican Republic  Caribbean  1.136420e+11  36.379291
71                            Haiti  Caribbean  2.025360e+10   6.483621

--- Central America ---
         country           region           gdp    gdp_pct
16        Belize  Central America  2.824080e+09   0.162603
131       Panama  Central America  7.652250e+10   4.405951
38    Costa Rica  Central America  6.838080e+10   3.937175
52   El Salvador  Central America  3.248870e+10   1.870608
123    Nicaragua  Central America  1.567160e+10   0.902327
72      Honduras  Central America  3.171770e+10   1.826216
67     Guatemala  Central America  9.500330e+10   5.470024
109       Mexico  Central America  1.414190e+12  81.425096

--- Central Asia ---
             country        region           gdp    gdp_pct
178     Turkmenistan  Central Asia  4.561060e+10  12.392562
90   Kyrgyz Republic  Central Asia  1.093060e+10   2.969883
167       Tajikistan  Central Asia  1.049210e+10   2.850741
85        Kazakhstan  Central Asia  2.206230e+11  59.944051
186       Uzbekistan  Central Asia  8.039190e+10  21.842764

--- Eastern Africa ---
        country          region           gdp    gdp_pct
148  Seychelles  Eastern Africa  1.588410e+09   0.315332
36      Comoros  Eastern Africa  1.242520e+09   0.246665
47     Djibouti  Eastern Africa  3.515110e+09   0.697821
108   Mauritius  Eastern Africa  1.289830e+10   2.560574
54      Eritrea  Eastern Africa  2.065000e+09   0.409944
26      Burundi  Eastern Africa  3.073410e+09   0.610134
141      Rwanda  Eastern Africa  1.331280e+10   2.642860
193    Zimbabwe  Eastern Africa  2.067810e+10   4.105021
154     Somalia  Eastern Africa  8.126110e+09   1.613197
192      Zambia  Eastern Africa  2.978450e+10   5.912826
101      Malawi  Eastern Africa  1.316470e+10   2.613459
100  Madagascar  Eastern Africa  1.495500e+10   2.968870
116  Mozambique  Eastern Africa  1.785150e+10   3.543884
180      Uganda  Eastern Africa  4.555920e+10   9.044424
86        Kenya  Eastern Africa  1.134200e+11  22.516166
168    Tanzania  Eastern Africa  7.570930e+10  15.029829
57     Ethiopia  Eastern Africa  1.267830e+11  25.168992

--- Eastern Asia ---
                      country        region           gdp    gdp_pct
113                  Mongolia  Eastern Asia  1.681090e+10   0.070408
44   Dem. People's Rep. Korea  Eastern Asia           NaN        NaN
88                      Korea  Eastern Asia  1.665250e+12   6.974460
83                      Japan  Eastern Asia  4.231140e+12  17.721013
34                      China  Eastern Asia  1.796320e+13  75.234120

--- Eastern Europe ---
             country          region           gdp    gdp_pct
111          Moldova  Eastern Europe  1.442090e+10   0.347341
151  Slovak Republic  Eastern Europe  1.154690e+11   2.781180
24          Bulgaria  Eastern Europe  8.904040e+10   2.144622
14           Belarus  Eastern Europe  7.279350e+10   1.753300
73           Hungary  Eastern Europe  1.787890e+11   4.306302
43    Czech Republic  Eastern Europe  2.909240e+11   7.007180
139          Romania  Eastern Europe  3.012620e+11   7.256180
136           Poland  Eastern Europe  6.881770e+11  16.575394
181          Ukraine  Eastern Europe  1.605030e+11   3.865867
140           Russia  Eastern Europe  2.240420e+12  53.962634

--- Melanesia ---
              country     region           gdp    gdp_pct
187           Vanuatu  Melanesia  9.835830e+08   2.577798
153   Solomon Islands  Melanesia  1.595710e+09   4.182075
58               Fiji  Melanesia  4.943250e+09  12.955387
132  Papua New Guinea  Melanesia  3.063340e+10  80.284741

--- Micronesia ---
              country      region          gdp    gdp_pct
119             Nauru  Micronesia  150922000.0  11.619780
130             Palau  Micronesia  217800000.0  16.768848
106  Marshall Islands  Micronesia  279668000.0  21.532186
110        Micronesia  Micronesia  427094000.0  32.882802
87           Kiribati  Micronesia  223353000.0  17.196384

--- Middle Africa ---
                      country         region           gdp    gdp_pct
144     São Tomé and Principe  Middle Africa  5.466800e+08   0.192321
53          Equatorial Guinea  Middle Africa  1.181390e+10   4.156108
61                      Gabon  Middle Africa  2.107170e+10   7.412985
31   Central African Republic  Middle Africa  2.382620e+09   0.838201
37                      Congo  Middle Africa  1.461550e+10   5.141706
156               South Sudan  Middle Africa  1.199780e+10   4.220804
32                       Chad  Middle Africa  1.270410e+10   4.469279
29                   Cameroon  Middle Africa  4.434160e+10  15.599293
4                      Angola  Middle Africa  1.067140e+11  37.541789
45            Dem. Rep. Congo  Middle Africa  5.806600e+10  20.427512

--- Northern Africa ---
     country           region           gdp    gdp_pct
96     Libya  Northern Africa  4.575230e+10   4.831684
176  Tunisia  Northern Africa  4.666490e+10   4.928060
115  Morocco  Northern Africa  1.341820e+11  14.170327
2    Algeria  Northern Africa  1.919130e+11  20.267025
162    Sudan  Northern Africa  5.166220e+10   5.455801
51     Egypt  Northern Africa  4.767480e+11  50.347103

--- Northern America ---
           country            region           gdp   gdp_pct
30          Canada  Northern America  2.139840e+12   7.75233
184  United States  Northern America  2.546270e+13  92.24767

--- Northern Europe ---
            country           region           gdp    gdp_pct
74          Iceland  Northern Europe  2.784160e+10   0.495510
55          Estonia  Northern Europe  3.810080e+10   0.678097
92           Latvia  Northern Europe  4.115390e+10   0.732435
98        Lithuania  Northern Europe  7.033430e+10   1.251771
79          Ireland  Northern Europe  5.292450e+11   9.419213
127          Norway  Northern Europe  5.792670e+11  10.309477
59          Finland  Northern Europe  2.808260e+11   4.997987
46          Denmark  Northern Europe  3.954040e+11   7.037184
164          Sweden  Northern Europe  5.859390e+11  10.428222
183  United Kingdom  Northern Europe  3.070670e+12  54.650104

--- Polynesia ---
    country     region          gdp    gdp_pct
179  Tuvalu  Polynesia   60349400.0   4.430942
174   Tonga  Polynesia  469228000.0  34.451410
142   Samoa  Polynesia  832422000.0  61.117648

--- South America ---
       country         region           gdp    gdp_pct
163   Suriname  South America  3.620660e+09   0.085944
70      Guyana  South America  1.535750e+10   0.364542
185    Uruguay  South America  7.117710e+10   1.689536
133   Paraguay  South America  4.172230e+10   0.990365
19     Bolivia  South America  4.306890e+10   1.022329
50     Ecuador  South America  1.150490e+11   2.730926
33       Chile  South America  3.010250e+11   7.145450
188  Venezuela  South America  4.823590e+11  11.449788
134       Peru  South America  2.426320e+11   5.759372
6    Argentina  South America  6.327700e+11  15.020104
35    Colombia  South America  3.439390e+11   8.164103
22      Brazil  South America  1.920100e+12  45.577542

--- South-Eastern Asia ---
         country              region           gdp    gdp_pct
23        Brunei  South-Eastern Asia  1.668150e+10   0.460114
172  Timor-Leste  South-Eastern Asia  3.163320e+09   0.087252
150    Singapore  South-Eastern Asia  4.667890e+11  12.875118
91       Lao PDR  South-Eastern Asia  1.572440e+10   0.433715
28      Cambodia  South-Eastern Asia  2.995680e+10   0.826278
102     Malaysia  South-Eastern Asia  4.063060e+11  11.206857
117      Myanmar  South-Eastern Asia  5.936440e+10   1.637407
169     Thailand  South-Eastern Asia  4.953410e+11  13.662648
189      Vietnam  South-Eastern Asia  4.088020e+11  11.275703
135  Philippines  South-Eastern Asia  4.042840e+11  11.151086
76     Indonesia  South-Eastern Asia  1.319100e+12  36.383822

--- Southern Africa ---
          country           region           gdp    gdp_pct
56       Eswatini  Southern Africa  4.854170e+09   1.087800
94        Lesotho  Southern Africa  2.553460e+09   0.572220
118       Namibia  Southern Africa  1.260740e+10   2.825268
21       Botswana  Southern Africa  2.035230e+10   4.560869
155  South Africa  Southern Africa  4.058700e+11  90.953843

--- Southern Asia ---
         country         region           gdp    gdp_pct
103     Maldives  Southern Asia  6.189870e+09   0.130343
18        Bhutan  Southern Asia  2.539550e+09   0.053476
158    Sri Lanka  Southern Asia  7.440360e+10   1.566750
120        Nepal  Southern Asia  4.082820e+10   0.859738
0    Afghanistan  Southern Asia  1.458310e+10   0.307083
77          Iran  Southern Asia  3.885440e+11   8.181747
12    Bangladesh  Southern Asia  4.602010e+11   9.690661
129     Pakistan  Southern Asia  3.765330e+11   7.928826
75         India  Southern Asia  3.385090e+12  71.281375

--- Southern Europe ---
                    country           region           gdp    gdp_pct
143              San Marino  Southern Europe  1.855380e+09   0.044281
3                   Andorra  Southern Europe  3.352030e+09   0.080000
105                   Malta  Southern Europe  1.776530e+10   0.423991
114              Montenegro  Southern Europe  6.095980e+09   0.145488
42                   Cyprus  Southern Europe  2.843910e+10   0.678735
126         North Macedonia  Southern Europe  1.356310e+10   0.323700
152                Slovenia  Southern Europe  6.211780e+10   1.482520
1                   Albania  Southern Europe  1.888210e+10   0.450645
20   Bosnia and Herzegovina  Southern Europe  2.452750e+10   0.585380
40                  Croatia  Southern Europe  7.096460e+10   1.693660
147                  Serbia  Southern Europe  6.350180e+10   1.515550
137                Portugal  Southern Europe  2.519450e+11   6.012985
65                   Greece  Southern Europe  2.190660e+11   5.228286
157                   Spain  Southern Europe  1.397510e+12  33.353336
81                    Italy  Southern Europe  2.010430e+12  47.981443

--- Western Africa ---
           country          region           gdp    gdp_pct
27      Cabo Verde  Western Africa  2.314820e+09   0.300262
69   Guinea-Bissau  Western Africa  1.633560e+09   0.211894
171     The Gambia  Western Africa  2.273060e+09   0.294845
107     Mauritania  Western Africa  1.037550e+10   1.345836
95         Liberia  Western Africa  4.001050e+09   0.518988
149   Sierra Leone  Western Africa  3.970340e+09   0.515004
173           Togo  Western Africa  8.126440e+09   1.054104
17           Benin  Western Africa  1.740170e+10   2.257225
68          Guinea  Western Africa  2.122770e+10   2.753506
146        Senegal  Western Africa  2.768440e+10   3.591023
104           Mali  Western Africa  1.882720e+10   2.442130
25    Burkina Faso  Western Africa  1.888460e+10   2.449576
124          Niger  Western Africa  1.396960e+10   1.812037
39   Côte d'Ivoire  Western Africa  7.001870e+10   9.082327
64           Ghana  Western Africa  7.283880e+10   9.448130
125        Nigeria  Western Africa  4.773860e+11  61.923113

--- Western Asia ---
                  country        region           gdp    gdp_pct
11                Bahrain  Western Asia  4.439080e+10   1.073774
138                 Qatar  Western Asia  2.372960e+11   5.739982
7                 Armenia  Western Asia  1.950280e+10   0.471756
62                Georgia  Western Asia  2.460540e+10   0.595183
89                 Kuwait  Western Asia  1.845580e+11   4.464296
128                  Oman  Western Asia  1.146670e+11   2.773694
190    West Bank and Gaza  Western Asia  1.911190e+10   0.462300
93                Lebanon  Western Asia  2.313190e+10   0.559540
182  United Arab Emirates  Western Asia  5.075350e+11  12.276825
80                 Israel  Western Asia  5.220330e+11  12.627519
10             Azerbaijan  Western Asia  7.872110e+10   1.904194
84                 Jordan  Western Asia  4.745150e+10   1.147810
166  Syrian Arab Republic  Western Asia  1.115930e+10   0.269934
191                 Yemen  Western Asia  2.160620e+10   0.522635
145          Saudi Arabia  Western Asia  1.108150e+12  26.805174
78                   Iraq  Western Asia  2.641820e+11   6.390330
177                Turkey  Western Asia  9.059880e+11  21.915053

--- Western Europe ---
           country          region           gdp    gdp_pct
112         Monaco  Western Europe  8.596160e+09   0.087698
97   Liechtenstein  Western Europe  7.186430e+09   0.073316
99      Luxembourg  Western Europe  8.227480e+10   0.839369
165    Switzerland  Western Europe  8.077060e+11   8.240231
9          Austria  Western Europe  4.714000e+11   4.809231
15         Belgium  Western Europe  5.786040e+11   5.902928
121    Netherlands  Western Europe  9.911150e+11  10.111373
60          France  Western Europe  2.782910e+12  28.391298
63         Germany  Western Europe  4.072190e+12  41.544555

In [179]:
df.describe(include=['object'])

,country,country_long,currency,capital_city,region,continent,demonym,democracy_type,political_leader,title
count,194,194,194,194,194,194,194,194,187,187
unique,194,194,142,194,22,5,192,5,187,17
top,Tuvalu,Tuvalu,Euro,Funafuti,Eastern Africa,Africa,Dominican,Flawed democracy,Kausea Natano,President
freq,1,1,23,1,17,54,2,53,1,99

In [180]:
# Perform a time-series-like analysis by assuming birth_rate and death_rate
# are annual metrics and estimate population growth rate.
df["growth_rate"] = ((df["birth_rate"] - df["death_rate"]) / 1000) * 100

result = df[["country", "birth_rate", "death_rate", "growth_rate"]]
print(result)

           country  birth_rate  death_rate  growth_rate
179         Tuvalu      23.484      10.159       1.3325
119          Nauru      27.560       6.633       2.0927
130          Palau      13.400      10.200       0.3200
143     San Marino       6.200       9.100      -0.2900
112         Monaco       5.900       6.600      -0.0700
..             ...         ...         ...          ...
129       Pakistan      27.519       7.168       2.0351
76       Indonesia      16.425      10.065       0.6360
184  United States      11.000      10.400       0.0600
34           China       7.520       7.180       0.0340
75           India      16.419       9.448       0.6971

[194 rows x 4 columns]

In [181]:
print(df["growth_rate"].describe())

count    194.000000
mean       1.043610
std        1.112096
min       -1.320000
25%        0.185475
50%        0.946700
75%        1.991175
max        3.715200
Name: growth_rate, dtype: float64

In [182]:
highest_growth = df.nlargest(5, "growth_rate")[["country", "growth_rate"]]
lowest_growth = df.nsmallest(5, "growth_rate")[["country", "growth_rate"]]
print("Highest Growth Rates:\n", highest_growth)
print("Lowest Growth Rates:\n", lowest_growth)

Highest Growth Rates:
                       country  growth_rate
124                     Niger       3.7152
104                      Mali       3.2369
45            Dem. Rep. Congo       3.2349
154                   Somalia       3.1965
31   Central African Republic       3.1287
Lowest Growth Rates:
        country  growth_rate
24    Bulgaria        -1.32
181    Ukraine        -1.12
147     Serbia        -1.09
92      Latvia        -0.92
98   Lithuania        -0.87

In [183]:
continent_growth = df.groupby("continent")["growth_rate"].mean().sort_values(ascending=False)
print(continent_growth)

continent
Africa      2.198009
Oceania     1.506186
Asia        1.092830
Americas    0.659406
Europe     -0.267295
Name: growth_rate, dtype: float64

In [184]:
correlation = df["growth_rate"].corr(df["gdp"])
print(f"Correlation between growth rate and GDP: {correlation}")

Correlation between growth rate and GDP: -0.17357820658704448

In [185]:
df.pivot_table()

ValueError: No group keys passed!

In [ ]:
global_mean_vulnerable_employment_pct=df["vulnerable_employment_pct"].mean()
global_median_self_employed_pct=df["self_employed_pct"].median()
df[(df["vulnerable_employment_pct"] > global_mean_vulnerable_employment_pct) & (df["self_employed_pct"] > global_median_self_employed_pct)]["country"]

174                    Tonga
144    São Tomé and Principe
187                  Vanuatu
153          Solomon Islands
18                    Bhutan
               ...
125                  Nigeria
129                 Pakistan
76                 Indonesia
34                     China
75                     India
Name: country, Length: 77, dtype: object

In [ ]:
 df.groupby(['continent', 'region'])['renewable_energy_consumption_pct'].mean()

continent  region
Africa     Eastern Africa               68.645294
           Middle Africa                64.227000
           Northern Africa              15.951667
           Southern Africa              33.866000
           Western Africa               60.846875
Americas   Caribbean                    13.065385
           Central America              37.490000
           Northern America             17.505000
           South America                29.916667
Asia       Central Asia                 14.332000
           Eastern Asia                  8.714000
           South-Eastern Asia           24.550909
           Southern Asia                37.957778
           Western Asia                  5.397059
Europe     Eastern Europe               15.514000
           Northern Europe              43.231000
           Southern Europe              25.500714
           Western Europe               24.597500
Oceania    Australia and New Zealand    19.750000
           Melanesia                    38.772500
           Micronesia                   11.972000
           Polynesia                    15.436667
Name: renewable_energy_consumption_pct, dtype: float64

In [ ]:
df.groupby(['region', 'continent'])['renewable_energy_consumption_pct'].mean()

region                     continent
Australia and New Zealand  Oceania      19.750000
Caribbean                  Americas     13.065385
Central America            Americas     37.490000
Central Asia               Asia         14.332000
Eastern Africa             Africa       68.645294
Eastern Asia               Asia          8.714000
Eastern Europe             Europe       15.514000
Melanesia                  Oceania      38.772500
Micronesia                 Oceania      11.972000
Middle Africa              Africa       64.227000
Northern Africa            Africa       15.951667
Northern America           Americas     17.505000
Northern Europe            Europe       43.231000
Polynesia                  Oceania      15.436667
South America              Americas     29.916667
South-Eastern Asia         Asia         24.550909
Southern Africa            Africa       33.866000
Southern Asia              Asia         37.957778
Southern Europe            Europe       25.500714
Western Africa             Africa       60.846875
Western Asia               Asia          5.397059
Western Europe             Europe       24.597500
Name: renewable_energy_consumption_pct, dtype: float64

In [188]:
# Apply a custom function to rank countries within each continent by gdp and
# add the rank as a new column
import pandas as pd

def rank_gdp(series):
    return series.rank(ascending=False, method='min')

df['gdp_rank'] = df.groupby('continent')['gdp'].transform(rank_gdp)

print(df[['country', 'continent', 'gdp', 'gdp_rank']])

                   country continent           gdp  gdp_rank
0               Seychelles    Africa  1.588410e+09      52.0
1    São Tomé and Principe    Africa  5.466800e+08      54.0
2               Cabo Verde    Africa  2.314820e+09      48.0
3                  Comoros    Africa  1.242520e+09      53.0
4                 Djibouti    Africa  3.515110e+09      44.0
..                     ...       ...           ...       ...
189        Solomon Islands   Oceania  1.595710e+09       5.0
190                   Fiji   Oceania  4.943250e+09       4.0
191            New Zealand   Oceania  2.472340e+11       2.0
192       Papua New Guinea   Oceania  3.063340e+10       3.0
193              Australia   Oceania  1.675420e+12       1.0

[194 rows x 4 columns]